// <auto-generated />
using System;
using JobsStats.API.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsStats.API.Migrations
{
    [DbContext(typeof(JobStatsDbContext))]
    [Migration("20221005192124_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobsStats.API.DB.Models.JobWatchesPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobWatchesPerDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 10, 5, 22, 21, 24, 224, DateTimeKind.Local).AddTicks(6040),
                            JobName = "El-al",
                            NumberOfWatches = 34
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            JobName = "Refael",
                            NumberOfWatches = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
