// <auto-generated />
using System;
using JobsStats.API.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsStats.API.Migrations
{
    [DbContext(typeof(JobStatsDbContext))]
    [Migration("20221005194543_v5")]
    partial class v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobsStats.API.DB.Models.JobWatchesPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobWatchesPerDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 10, 5, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4893),
                            JobName = "refael",
                            NumberOfWatches = 32
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 5, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4928),
                            JobName = "elal",
                            NumberOfWatches = 59
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 10, 5, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4931),
                            JobName = "elbit",
                            NumberOfWatches = 22
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 10, 6, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4933),
                            JobName = "refael",
                            NumberOfWatches = 17
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 10, 6, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4935),
                            JobName = "elal",
                            NumberOfWatches = 65
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 10, 6, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4938),
                            JobName = "elbit",
                            NumberOfWatches = 38
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 10, 6, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4940),
                            JobName = "tnuva",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 10, 6, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4942),
                            JobName = "nova",
                            NumberOfWatches = 66
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 10, 7, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4944),
                            JobName = "refael",
                            NumberOfWatches = 2
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 10, 8, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4946),
                            JobName = "refael",
                            NumberOfWatches = 53
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 10, 8, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4948),
                            JobName = "elal",
                            NumberOfWatches = 5
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 10, 8, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4950),
                            JobName = "elbit",
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 10, 9, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4952),
                            JobName = "refael",
                            NumberOfWatches = 59
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 10, 9, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4954),
                            JobName = "elal",
                            NumberOfWatches = 37
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 10, 9, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4955),
                            JobName = "elbit",
                            NumberOfWatches = 7
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 10, 9, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4957),
                            JobName = "tnuva",
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 10, 10, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4959),
                            JobName = "refael",
                            NumberOfWatches = 54
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 10, 10, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4961),
                            JobName = "elal",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 10, 10, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4963),
                            JobName = "elbit",
                            NumberOfWatches = 69
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 10, 11, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4965),
                            JobName = "refael",
                            NumberOfWatches = 35
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 10, 11, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4967),
                            JobName = "elal",
                            NumberOfWatches = 56
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 10, 14, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4969),
                            JobName = "refael",
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 10, 16, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4971),
                            JobName = "refael",
                            NumberOfWatches = 35
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 10, 16, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4972),
                            JobName = "elal",
                            NumberOfWatches = 27
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 10, 16, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4974),
                            JobName = "elbit",
                            NumberOfWatches = 12
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 10, 17, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4976),
                            JobName = "refael",
                            NumberOfWatches = 56
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 10, 17, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4978),
                            JobName = "elal",
                            NumberOfWatches = 7
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 10, 17, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4979),
                            JobName = "elbit",
                            NumberOfWatches = 50
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 10, 18, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4981),
                            JobName = "refael",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 10, 18, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4983),
                            JobName = "elal",
                            NumberOfWatches = 28
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 10, 18, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4985),
                            JobName = "elbit",
                            NumberOfWatches = 31
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 10, 18, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4986),
                            JobName = "tnuva",
                            NumberOfWatches = 67
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 10, 20, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4988),
                            JobName = "refael",
                            NumberOfWatches = 36
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 10, 20, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4991),
                            JobName = "elal",
                            NumberOfWatches = 47
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 10, 20, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4992),
                            JobName = "elbit",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 10, 21, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4994),
                            JobName = "refael",
                            NumberOfWatches = 66
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 10, 21, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4996),
                            JobName = "elal",
                            NumberOfWatches = 67
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 10, 21, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4997),
                            JobName = "elbit",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 10, 22, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(4999),
                            JobName = "refael",
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 10, 22, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5001),
                            JobName = "elal",
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 10, 23, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5003),
                            JobName = "refael",
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 10, 24, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5004),
                            JobName = "refael",
                            NumberOfWatches = 65
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 10, 24, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5006),
                            JobName = "elal",
                            NumberOfWatches = 33
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 10, 24, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5008),
                            JobName = "elbit",
                            NumberOfWatches = 29
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 10, 24, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5010),
                            JobName = "tnuva",
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2022, 10, 25, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5012),
                            JobName = "refael",
                            NumberOfWatches = 49
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2022, 10, 26, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5013),
                            JobName = "refael",
                            NumberOfWatches = 68
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2022, 10, 26, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5015),
                            JobName = "elal",
                            NumberOfWatches = 3
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2022, 10, 27, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5017),
                            JobName = "refael",
                            NumberOfWatches = 45
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2022, 10, 27, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5018),
                            JobName = "elal",
                            NumberOfWatches = 16
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2022, 10, 29, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5020),
                            JobName = "refael",
                            NumberOfWatches = 19
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2022, 10, 29, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5022),
                            JobName = "elal",
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2022, 10, 29, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5023),
                            JobName = "elbit",
                            NumberOfWatches = 65
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2022, 10, 31, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5026),
                            JobName = "refael",
                            NumberOfWatches = 38
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2022, 10, 31, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5027),
                            JobName = "elal",
                            NumberOfWatches = 68
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2022, 10, 31, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5029),
                            JobName = "elbit",
                            NumberOfWatches = 64
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2022, 10, 31, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5031),
                            JobName = "tnuva",
                            NumberOfWatches = 4
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2022, 11, 2, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5033),
                            JobName = "refael",
                            NumberOfWatches = 17
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2022, 11, 2, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5034),
                            JobName = "elal",
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2022, 11, 2, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5036),
                            JobName = "elbit",
                            NumberOfWatches = 22
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2022, 11, 3, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5038),
                            JobName = "refael",
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2022, 11, 3, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5040),
                            JobName = "elal",
                            NumberOfWatches = 26
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2022, 11, 3, 22, 45, 43, 238, DateTimeKind.Local).AddTicks(5077),
                            JobName = "elbit",
                            NumberOfWatches = 54
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
