// <auto-generated />
using System;
using JobsStats.API.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsStats.API.Migrations
{
    [DbContext(typeof(JobStatsDbContext))]
    [Migration("20221005194726_v6")]
    partial class v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobsStats.API.DB.Models.JobWatchesPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobWatchesPerDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 10, 5, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9333),
                            JobName = "refael",
                            NumberOfWatches = 41
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 5, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9369),
                            JobName = "elal",
                            NumberOfWatches = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 10, 5, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9372),
                            JobName = "elbit",
                            NumberOfWatches = 66
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 10, 6, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9374),
                            JobName = "refael",
                            NumberOfWatches = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 10, 6, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9376),
                            JobName = "elal",
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 10, 6, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9380),
                            JobName = "elbit",
                            NumberOfWatches = 50
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 10, 8, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9382),
                            JobName = "refael",
                            NumberOfWatches = 16
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 10, 8, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9384),
                            JobName = "elal",
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 10, 9, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9420),
                            JobName = "refael",
                            NumberOfWatches = 46
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 10, 10, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9423),
                            JobName = "refael",
                            NumberOfWatches = 48
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 10, 10, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9425),
                            JobName = "elal",
                            NumberOfWatches = 69
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 10, 11, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9427),
                            JobName = "refael",
                            NumberOfWatches = 36
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 10, 11, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9429),
                            JobName = "elal",
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 10, 11, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9431),
                            JobName = "elbit",
                            NumberOfWatches = 1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 10, 12, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9432),
                            JobName = "refael",
                            NumberOfWatches = 66
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 10, 13, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9434),
                            JobName = "refael",
                            NumberOfWatches = 39
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 10, 13, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9436),
                            JobName = "elal",
                            NumberOfWatches = 56
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 10, 14, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9438),
                            JobName = "refael",
                            NumberOfWatches = 68
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 10, 14, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9440),
                            JobName = "elal",
                            NumberOfWatches = 48
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 10, 15, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9442),
                            JobName = "refael",
                            NumberOfWatches = 55
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 10, 16, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9444),
                            JobName = "refael",
                            NumberOfWatches = 51
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 10, 18, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9446),
                            JobName = "refael",
                            NumberOfWatches = 42
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 10, 19, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9448),
                            JobName = "refael",
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 10, 19, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9449),
                            JobName = "elal",
                            NumberOfWatches = 55
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 10, 20, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9451),
                            JobName = "refael",
                            NumberOfWatches = 17
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 10, 23, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9454),
                            JobName = "refael",
                            NumberOfWatches = 9
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 10, 23, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9456),
                            JobName = "elal",
                            NumberOfWatches = 53
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 10, 23, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9458),
                            JobName = "elbit",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 10, 24, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9459),
                            JobName = "refael",
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 10, 25, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9461),
                            JobName = "refael",
                            NumberOfWatches = 19
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 10, 25, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9463),
                            JobName = "elal",
                            NumberOfWatches = 5
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 10, 27, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9465),
                            JobName = "refael",
                            NumberOfWatches = 25
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 10, 28, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9467),
                            JobName = "refael",
                            NumberOfWatches = 42
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 10, 28, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9469),
                            JobName = "elal",
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 10, 28, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9471),
                            JobName = "elbit",
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 10, 29, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9473),
                            JobName = "refael",
                            NumberOfWatches = 59
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 10, 29, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9475),
                            JobName = "elal",
                            NumberOfWatches = 28
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 10, 29, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9477),
                            JobName = "elbit",
                            NumberOfWatches = 32
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 10, 30, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9479),
                            JobName = "refael",
                            NumberOfWatches = 51
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 10, 30, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9481),
                            JobName = "elal",
                            NumberOfWatches = 65
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 10, 31, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9483),
                            JobName = "refael",
                            NumberOfWatches = 27
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 10, 31, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9484),
                            JobName = "elal",
                            NumberOfWatches = 51
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 11, 1, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9486),
                            JobName = "refael",
                            NumberOfWatches = 31
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 11, 2, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9488),
                            JobName = "refael",
                            NumberOfWatches = 41
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 11, 3, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9490),
                            JobName = "refael",
                            NumberOfWatches = 33
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2022, 11, 3, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9492),
                            JobName = "elal",
                            NumberOfWatches = 18
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2022, 11, 3, 22, 47, 26, 685, DateTimeKind.Local).AddTicks(9494),
                            JobName = "elbit",
                            NumberOfWatches = 32
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
