// <auto-generated />
using System;
using JobsStats.API.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsStats.API.Migrations
{
    [DbContext(typeof(JobStatsDbContext))]
    partial class JobStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobsStats.API.DB.Models.JobWatchesPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobWatchesPerDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(123),
                            JobId = 0,
                            NumberOfWatches = 49
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(160),
                            JobId = 1,
                            NumberOfWatches = 24
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(163),
                            JobId = 2,
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(164),
                            JobId = 3,
                            NumberOfWatches = 13
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(166),
                            JobId = 4,
                            NumberOfWatches = 41
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(169),
                            JobId = 5,
                            NumberOfWatches = 13
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(200),
                            JobId = 6,
                            NumberOfWatches = 15
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(202),
                            JobId = 0,
                            NumberOfWatches = 47
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(204),
                            JobId = 1,
                            NumberOfWatches = 40
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(206),
                            JobId = 2,
                            NumberOfWatches = 22
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(208),
                            JobId = 3,
                            NumberOfWatches = 16
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(209),
                            JobId = 4,
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(211),
                            JobId = 5,
                            NumberOfWatches = 4
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 10, 8, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(212),
                            JobId = 0,
                            NumberOfWatches = 28
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 10, 9, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(214),
                            JobId = 0,
                            NumberOfWatches = 8
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 10, 9, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(215),
                            JobId = 1,
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 10, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(217),
                            JobId = 0,
                            NumberOfWatches = 45
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 10, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(220),
                            JobId = 1,
                            NumberOfWatches = 61
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 10, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(221),
                            JobId = 2,
                            NumberOfWatches = 14
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 10, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(223),
                            JobId = 3,
                            NumberOfWatches = 30
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 10, 11, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(225),
                            JobId = 0,
                            NumberOfWatches = 56
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 10, 11, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(226),
                            JobId = 1,
                            NumberOfWatches = 60
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 10, 12, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(228),
                            JobId = 0,
                            NumberOfWatches = 35
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 10, 12, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(229),
                            JobId = 1,
                            NumberOfWatches = 16
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 10, 12, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(231),
                            JobId = 2,
                            NumberOfWatches = 7
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 10, 13, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(233),
                            JobId = 0,
                            NumberOfWatches = 52
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 10, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(235),
                            JobId = 0,
                            NumberOfWatches = 38
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 10, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(237),
                            JobId = 1,
                            NumberOfWatches = 34
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 10, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(238),
                            JobId = 2,
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 10, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(240),
                            JobId = 3,
                            NumberOfWatches = 2
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 10, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(242),
                            JobId = 0,
                            NumberOfWatches = 21
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 10, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(243),
                            JobId = 1,
                            NumberOfWatches = 39
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 10, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(245),
                            JobId = 2,
                            NumberOfWatches = 46
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 10, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(247),
                            JobId = 3,
                            NumberOfWatches = 19
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 10, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(249),
                            JobId = 0,
                            NumberOfWatches = 62
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 10, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(250),
                            JobId = 1,
                            NumberOfWatches = 51
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 10, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(252),
                            JobId = 2,
                            NumberOfWatches = 34
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 10, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(254),
                            JobId = 3,
                            NumberOfWatches = 4
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 10, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(255),
                            JobId = 0,
                            NumberOfWatches = 29
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 10, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(257),
                            JobId = 1,
                            NumberOfWatches = 13
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 10, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(258),
                            JobId = 2,
                            NumberOfWatches = 20
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 10, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(260),
                            JobId = 3,
                            NumberOfWatches = 59
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 10, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(262),
                            JobId = 0,
                            NumberOfWatches = 55
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 10, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(263),
                            JobId = 1,
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 10, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(265),
                            JobId = 2,
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2022, 10, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(266),
                            JobId = 3,
                            NumberOfWatches = 25
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(268),
                            JobId = 0,
                            NumberOfWatches = 3
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(270),
                            JobId = 1,
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(272),
                            JobId = 2,
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(273),
                            JobId = 3,
                            NumberOfWatches = 69
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(275),
                            JobId = 4,
                            NumberOfWatches = 3
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(276),
                            JobId = 5,
                            NumberOfWatches = 41
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(278),
                            JobId = 6,
                            NumberOfWatches = 58
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2022, 10, 20, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(279),
                            JobId = 0,
                            NumberOfWatches = 68
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2022, 10, 20, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(281),
                            JobId = 1,
                            NumberOfWatches = 55
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2022, 10, 20, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(282),
                            JobId = 2,
                            NumberOfWatches = 33
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2022, 10, 20, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(284),
                            JobId = 3,
                            NumberOfWatches = 61
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2022, 10, 21, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(286),
                            JobId = 0,
                            NumberOfWatches = 34
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2022, 10, 21, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(288),
                            JobId = 1,
                            NumberOfWatches = 39
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2022, 10, 21, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(289),
                            JobId = 2,
                            NumberOfWatches = 37
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2022, 10, 23, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(291),
                            JobId = 0,
                            NumberOfWatches = 54
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2022, 10, 23, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(293),
                            JobId = 1,
                            NumberOfWatches = 60
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2022, 10, 23, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(294),
                            JobId = 2,
                            NumberOfWatches = 26
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2022, 10, 24, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(296),
                            JobId = 0,
                            NumberOfWatches = 9
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2022, 10, 24, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(297),
                            JobId = 1,
                            NumberOfWatches = 36
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2022, 10, 24, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(300),
                            JobId = 2,
                            NumberOfWatches = 47
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2022, 10, 24, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(301),
                            JobId = 3,
                            NumberOfWatches = 67
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2022, 10, 25, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(303),
                            JobId = 0,
                            NumberOfWatches = 53
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2022, 10, 27, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(305),
                            JobId = 0,
                            NumberOfWatches = 9
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2022, 10, 27, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(307),
                            JobId = 1,
                            NumberOfWatches = 27
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2022, 10, 27, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(308),
                            JobId = 2,
                            NumberOfWatches = 14
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2022, 10, 27, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(310),
                            JobId = 3,
                            NumberOfWatches = 40
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2022, 10, 28, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(312),
                            JobId = 0,
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2022, 10, 28, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(313),
                            JobId = 1,
                            NumberOfWatches = 29
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2022, 10, 28, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(315),
                            JobId = 2,
                            NumberOfWatches = 28
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2022, 10, 29, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(316),
                            JobId = 0,
                            NumberOfWatches = 56
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2022, 10, 29, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(318),
                            JobId = 1,
                            NumberOfWatches = 26
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(319),
                            JobId = 0,
                            NumberOfWatches = 28
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(321),
                            JobId = 1,
                            NumberOfWatches = 67
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(323),
                            JobId = 2,
                            NumberOfWatches = 60
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(324),
                            JobId = 3,
                            NumberOfWatches = 13
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(326),
                            JobId = 4,
                            NumberOfWatches = 4
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(328),
                            JobId = 5,
                            NumberOfWatches = 23
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2022, 10, 31, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(329),
                            JobId = 0,
                            NumberOfWatches = 3
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2022, 10, 31, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(331),
                            JobId = 1,
                            NumberOfWatches = 43
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2022, 10, 31, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(332),
                            JobId = 2,
                            NumberOfWatches = 16
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2022, 11, 2, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(334),
                            JobId = 0,
                            NumberOfWatches = 69
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2022, 11, 2, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(336),
                            JobId = 1,
                            NumberOfWatches = 47
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2022, 11, 2, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(337),
                            JobId = 2,
                            NumberOfWatches = 32
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2022, 11, 3, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(339),
                            JobId = 0,
                            NumberOfWatches = 11
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2022, 11, 3, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(340),
                            JobId = 1,
                            NumberOfWatches = 25
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2022, 11, 3, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(342),
                            JobId = 2,
                            NumberOfWatches = 12
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2022, 11, 3, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(343),
                            JobId = 3,
                            NumberOfWatches = 39
                        });
                });

            modelBuilder.Entity("JobsStats.API.DB.Models.PredictedJobWatchesPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredictedNumberOfWatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PredictedJobWatchesPerDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 10, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(388),
                            PredictedNumberOfWatches = 30
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(392),
                            PredictedNumberOfWatches = 7
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 10, 8, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(393),
                            PredictedNumberOfWatches = 14
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 10, 9, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(395),
                            PredictedNumberOfWatches = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 10, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(418),
                            PredictedNumberOfWatches = 8
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 10, 11, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(420),
                            PredictedNumberOfWatches = 59
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 10, 12, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(422),
                            PredictedNumberOfWatches = 14
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 10, 13, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(424),
                            PredictedNumberOfWatches = 35
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 10, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(426),
                            PredictedNumberOfWatches = 38
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 10, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(427),
                            PredictedNumberOfWatches = 26
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 10, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(429),
                            PredictedNumberOfWatches = 3
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 10, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(431),
                            PredictedNumberOfWatches = 13
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 10, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(433),
                            PredictedNumberOfWatches = 50
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 10, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(434),
                            PredictedNumberOfWatches = 33
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 10, 20, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(436),
                            PredictedNumberOfWatches = 13
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 10, 21, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(437),
                            PredictedNumberOfWatches = 68
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 10, 22, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(439),
                            PredictedNumberOfWatches = 69
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 10, 23, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(441),
                            PredictedNumberOfWatches = 56
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 10, 24, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(442),
                            PredictedNumberOfWatches = 45
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 10, 25, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(444),
                            PredictedNumberOfWatches = 8
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 10, 26, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(445),
                            PredictedNumberOfWatches = 64
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 10, 27, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(446),
                            PredictedNumberOfWatches = 31
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 10, 28, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(448),
                            PredictedNumberOfWatches = 45
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 10, 29, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(449),
                            PredictedNumberOfWatches = 45
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 10, 30, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(451),
                            PredictedNumberOfWatches = 19
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 10, 31, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(452),
                            PredictedNumberOfWatches = 16
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 11, 1, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(453),
                            PredictedNumberOfWatches = 11
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 11, 2, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(455),
                            PredictedNumberOfWatches = 67
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 11, 3, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(457),
                            PredictedNumberOfWatches = 28
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 11, 4, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(458),
                            PredictedNumberOfWatches = 20
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 11, 5, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(459),
                            PredictedNumberOfWatches = 20
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 11, 6, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(461),
                            PredictedNumberOfWatches = 47
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 11, 7, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(462),
                            PredictedNumberOfWatches = 10
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 11, 8, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(464),
                            PredictedNumberOfWatches = 38
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 11, 9, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(465),
                            PredictedNumberOfWatches = 57
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 11, 10, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(467),
                            PredictedNumberOfWatches = 61
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 11, 11, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(468),
                            PredictedNumberOfWatches = 65
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 11, 12, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(470),
                            PredictedNumberOfWatches = 62
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 11, 13, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(471),
                            PredictedNumberOfWatches = 39
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 11, 14, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(473),
                            PredictedNumberOfWatches = 64
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 11, 15, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(474),
                            PredictedNumberOfWatches = 42
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 11, 16, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(476),
                            PredictedNumberOfWatches = 24
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 11, 17, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(477),
                            PredictedNumberOfWatches = 57
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 11, 18, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(479),
                            PredictedNumberOfWatches = 60
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 11, 19, 22, 52, 11, 822, DateTimeKind.Local).AddTicks(480),
                            PredictedNumberOfWatches = 26
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
